title: SuperParametIzation package
description: Software for superparameterization
author: Andy Davis
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
   math_engine: mathjax
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
